trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
- name: "namespace"
  value: "mysql-ns"

steps:
- task: Kubernetes@1
  displayName: Creating $(namespace) Namespace
  enabled: true
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'aks-connection'
    command: 'create'
    arguments: 'namespace $(namespace)'

- task: Kubernetes@1
  displayName: Creating Resource Quota for $(namespace) Namespace
  enabled: true
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'aks-connection'
    namespace: '$(namespace)'
    command: 'create'
    useConfigurationFile: true
    configuration: 'resourcequota.yml'

- task: Kubernetes@1
  displayName: Creating Storage Class with Azure File to Azure Kubernetes Service
  enabled: true
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'aks-connection'
    command: 'create'
    useConfigurationFile: true
    configuration: 'storageclass.yml'

- task: Kubernetes@1
  displayName: Deploying MySQL to Azure Kubernetes Service
  enabled: true
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'aks-connection'
    namespace: $(namespace)
    command: 'create'
    useConfigurationFile: true
    configuration: 'persistentvolumeclaim.yml deployment.yml service.yml'

