name: AKS RabbitMQ Deployment  

on: workflow_dispatch

permissions:
  id-token: write
  contents: read
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Azure Kubernetes set context
      uses: Azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
        cluster-name: ${{ secrets.AZURE_CLUSTER_NAME }}
    
    - name: Creating mysql-ns Namespace
      uses: Azure/k8s-deploy@v1
      with:        
        manifests: |
          namespace.yml
        action: deploy

    - name: Creating Resource Quota for mysql-ns Namespace
      uses: Azure/k8s-deploy@v1
      with:        
        namespace: mysql-ns
        manifests: |
          resourcequota.yml
        action: deploy
        
    - name: Creating Storage Class with Azure File to Azure Kubernetes Service
      uses: Azure/k8s-deploy@v1
      with:
        namespace: mysql-ns
        manifests: |
          storageclass.yml
        action: deploy
        
    - name: Creating MySQL to Azure Kubernetes Service
      uses: Azure/k8s-deploy@v1
      with:
        namespace: mysql-ns
        manifests: |
          persistentvolumeclaim.yml
          deployment.yml
          service.yml
        action: deploy
        
